### ISSUE TITLE
url automatic transform

### ISSUE THREAD

**Issue by AdrianZhou** [patrick96/click-link#1]
When I open 'http://www.cc98.org/dispbbs.asp?boardid=80&id=4643677', it wil automatic transform to 'http://www.cc98.org/dispbbs.asp?boardid=80&amp;id=4643677'. So I can't open the url correctly.
Hope you can fix it, thank you!

**Comment by patrick96** [comment]
Sorry I didn't respond earlier. I didn't get a mail
But it should be fixed now. Let me know if you still have any problems.
