### ISSUE TITLE
not working on Mac OS

### ISSUE THREAD

**Issue by janpom** [patrick96/click-link#2]
This is not working on a Mac OS (v10.11.6) since ctrl+click is interpreted as right-click. Would it be possible to change it to cmd+click for a Mac?

**Comment by patrick96** [comment]
I have just pushed an update that allows the meta key to be pressed as well (which I assume is the command key on mac os)
Unfortunately I have no mac to test that on, so could you please go ahead and update to 1.0.4 of the click-link package and you probably need to fully restart atom as well.

If it doesn't work for you, I will need you to gather some information on the click event but more info on that, if you confirm that it is indeed still not working

**Comment by janpom** [comment]
That was quick! Works like a charm now (with cmd+click). Thanks a lot.

čt 6. 10. 2016 v 17:05 odesílatel Patrick Ziegler notifications@github.com
napsal:

**Comment by patrick96** [comment]
Awesome!

closing
