### ISSUE TITLE
double-cursor

### ISSUE THREAD

**Issue by thornedlove** [patrick96/click-link#3]
The CTRL-click creates a double-cursor (document wise) if the mouse-click isn't pointed directly over the document cursor. This can be rid of by another mouse-click anywhere in the said document. 
![click-link-double-cursor](https://cloud.githubusercontent.com/assets/23011695/19626011/6ebb837c-98f5-11e6-9960-623bd910af9d.png)

**Comment by patrick96** [comment]
I hope this fixes it for you (it did for me)

The only thing you need to be careful about is when you already have multiple cursors, one of them inside a link, and then you ctrl-click exactly where the cursor inside the link is, this will remove the cursor inside the link, but this should be extremely rare.

**Comment by thornedlove** [comment]
It works fine on my side too.

Thanks for the fix.
