### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by pdxwolfy** [patrick96/click-link#5]
Upon upgrading to 1.0.6, I'm getting this message when clicking on any button or link in the settings page. When I try to create an issue with the "Create issue on the click-link package", I get a 414 Request-URI Too Large message.

```
/Users/wolfy/.atom/packages/click-link/lib/click-link.js:13
Hide Stack Trace
TypeError: Cannot read property 'getGrammar' of undefined
    at atom-pane-container.<anonymous> (/Users/wolfy/.atom/packages/click-link/lib/click-link.js:13:66)
```

I tried uninstalling and reinstalling, but that failed. I've reverted to 1.0.5 in the meantime.

**Comment by patrick96** [comment]
Sorry about that, somehow I didn't get a notification about that, just a message in the console.
But should be fixed now

**Comment by pdxwolfy** [comment]
That seems to have done the trick. Thanks for the quick fix.
