### ISSUE TITLE
install fails from atom & apm

### ISSUE THREAD

**Issue by thornedlove** [patrick96/click-link#6]
The 1.0.7 version doesn't install both from Atom or with the apm install in the said directory. 
The 1.0.5 version works perfectly well. 
This is probably a bug not due directly with your package since others have installed it successfully.

I run a Windows 10.
Atom version 1.12.6 

(included debug.txt)  
[npm-debug.txt](https://github.com/patrick96/click-link/files/628784/npm-debug.txt)
file)

**Comment by patrick96** [comment]
I have not been able to reproduce this on a clean atom install on windows

What's the output of running `atom -v`? Your node seems to be out of date

**Comment by thornedlove** [comment]
C:\Users\tonti>atom -v

Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

C:\Users\tonti>

**Comment by patrick96** [comment]
Ok your node seem up to date although in the log it mentions node v4.4.5.
This is an issue with oniguruma and not with click-link (since v1.0.6 oniguruma is a dependency so that's why 1.0.5 works for you).

You can open a new issue [here](https://github.com/atom/node-oniguruma/issues), they are more likely to be able help you than I am, since I cannot reproduce this.

I will keep this issue open for future reference, and also be sure to comment on here with the link to the new issue so others with the same problem can see it.

**Comment by thornedlove** [comment]
the node 4.4.5 is with 

C:\Users\tonti>apm -v
apm  1.12.9
npm  3.10.5
node 4.4.5
python
git
visual studio 2013

I've read that there are issues with visual studio 2013. I'll look into those and comment back if a solution is found. Thank you.

**Comment by lucascosti** [comment]
I am getting a similar problem of the update to 1.0.7 failing for this package (all my other packages update fine), 

Atom 1.12.6 on Fedora 24.

Log below:

````
/bin/bash: module: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_module'
/bin/bash: scl: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_scl'


> oniguruma@6.1.1 install /tmp/apm-install-dir-116117-10381-adjazg/node_modules/click-link/node_modules/oniguruma
> node-gyp rebuild


sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.10-200.fc24.x86_64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116117-10381-adjazg/node_modules/click-link/node_modules/oniguruma
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-116117-10381-adjazg/package.json'
npm WARN apm-install-dir-116117-10381-adjazg No description
npm WARN apm-install-dir-116117-10381-adjazg No repository field.
npm WARN apm-install-dir-116117-10381-adjazg No README data
npm WARN apm-install-dir-116117-10381-adjazg No license field.
npm ERR! Linux 4.8.10-200.fc24.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/lcosti/.atom/.apm/.apmrc" "--userconfig" "/home/lcosti/.atom/.apmrc" "install" "/tmp/d-116117-10381-1ptnhgq/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116117-10381-adjazg/npm-debug.log
`````

**Comment by patrick96** [comment]
Yes they look very similar. This one's even stranger.
I really have no idea why this would fail, the only thing I changed is that I added the dependency to oniguruma and it works fine on my end on both Linux and Windows.

For now you probably should just stay on 1.0.5 since the only feature that's missing there is proper markdown support.

@thornedlove have you already figured something out or opened an issue in the oniguruma repo?

**Comment by thornedlove** [comment]
I tried for a whole day to resolve the problem without success. I've read the oniguruma comments and one similar was issued a few months ago. I'm using another software that better suits my programming needs.

**Comment by gluons** [comment]
Same issue with [`oniguruma`](https://github.com/atom/node-oniguruma) 

My Atom version:
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

I have no idea with `oniguruma`. I see many issues on `oniguruma` that have not been replied or solved.

Some `oniguruma`'s **install fail** issue since 2014 still haven't been solved.

[error-log.txt](https://github.com/patrick96/click-link/files/661391/error-log.txt)

> Atom without `click-link` is sad 😢

**Comment by patrick96** [comment]
I have no idea why this oniguruma thing happens or how to solve it :(

I will be reverting the changes that required oniguruma as a dependency and I will try to accomplish what oniguruma was doing without any dependencies.

**Comment by patrick96** [comment]
Alright, I just pushed an update, I hope the installation goes smooth now with 1.0.8

**Comment by lucascosti** [comment]
Upgrade to 1.0.9 now worked for me :)
