### ISSUE TITLE
Deprecated selector in `click-link/styles/click-link.less`

### ISSUE THREAD

**Issue by PixelT** [patrick96/click-link#7]
In `click-link/styles/click-link.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .hyperlink:hover` => `atom-text-editor.editor .syntax--hyperlink:hover`

* `atom-text-editor::shadow .source.gfm .link:hover` => `atom-text-editor.editor .syntax--source.syntax--gfm .syntax--link:hover`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by patrick96** [comment]
Thanks for the notice, I'll have a look at it tomorrow

**Comment by ola456** [comment]
Changes in `click-link/styles/click-link.less`:
- `atom-text-editor::shadow .hyperlink:hover` => `atom-text-editor.editor .syntax--hyperlink:hover`
- `atom-text-editor::shadow .source.gfm .link:hover` => `atom-text-editor.editor .syntax--source.syntax--gfm .syntax--link:hover`

Changes in `click-link/lib/click-link.js`:
- `if(path.classList.contains("hyperlink") > 0)` => `if(path.classList.contains("syntax--hyperlink") > 0)`
- `else if(isMarkdown && path.classList.contains("link") > 0)` => `else if(isMarkdown && path.classList.contains("syntax--link") > 0)`
- `var child = path.querySelector(".link");` => `var child = path.querySelector(".syntax--link");`

& it works again!

**Comment by patrick96** [comment]
Thank you very much for the additional updates. Fix should be up in a few minutes

**Comment by patrick96** [comment]
Fix is up and in v1.0.10. Tell me if I missed anything
