### ISSUE TITLE
DOM Selector no longer works in 1.17.0

### ISSUE THREAD

**Issue by jonathanrdelgado** [patrick96/click-link#9]
Atom redid panes in 1.17.0, these changes affected the DOM, and thus the query selector for this package.

I was able to fix this locally by changing the query selector from `atom-pane-container.panes` to `atom-workspace`. Just passing it along in case you wanted to fix it upstream!

**Comment by patrick96** [comment]
Thanks for reporting
It seems `atom-pane-container.panes` still exists, but if selecting it via `querySelector` and then binding an eventListener, that eventListener is somehow lost, I don't know why.

I now stopped using `querySelector` for that and now use `atom.workspace.activePaneContainer.paneContainer.element`, which seems to work.

New version will be up in a minute
